### ISSUE TITLE
SA for Fithub project

### ISSUE THREAD

**Issue by ZYZMarshall** [ZYZMarshall/Fithub-project#1]
Architectures and related issues:
1. Decide how many tiers are needed for the website.
2. Identify the content of each layer.
3. Architecture review.

**Comment by ZYZMarshall** [comment]
Check this file out, I'm considering we could build our architecture base on the model in the file.
[SA 690.docx](https://github.com/ZYZMarshall/Fithub-project/files/2849793/SA.690.docx)

**Comment by WeihanRua** [comment]
[690 architect (1).pdf](https://github.com/ZYZMarshall/Fithub-project/files/2857342/690.architect.1.pdf)

**Comment by WeihanRua** [comment]
the relaxed-layer style architecture
